# Generated by Django 5.1.2 on 2024-12-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_order_options_rename_date_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
